<?php
$content = file_get_contents('app/Http/Controllers/ObePortalController.php');

$new_cases = <<<'EOD'
        switch ($key) {
            // NEW AUTOGENERATED PPEPP
            case "C1_P1":
                $title = "Penetapan Visi Keilmuan & Profil Program Studi (Penetapan C.1)";
                $data = \Illuminate\Support\Facades\DB::table("profil_prodis")->get();
                break;
            case "C1_P3_SurveiVisi":
                $title = "Laporan Evaluasi Pemahaman Visi Misi (Evaluasi C.1)";
                $data = \Illuminate\Support\Facades\DB::table("survei_kepuasans")
                    ->where("jenis_survei", "LIKE", "%Visi Misi%")
                    ->get();
                break;
            case "C2_P2_IA":
                $title = "Dokumen Implementation Arrangement / Perjanjian Kerja Sama (Pelaksanaan C.2)";
                $data = \Illuminate\Support\Facades\DB::table("pks_ia")->get();
                break;
            case "C6_P1_CPL":
                $title = "Penetapan Capaian Pembelajaran Lulusan / CPL (Penetapan C.6)";
                $data = \Illuminate\Support\Facades\DB::table("cpls")->get();
                break;
            case "C6_P3_Nilai":
                $title = "Evaluasi Ketercapaian CPL / CPMK Mahasiswa (Evaluasi C.6)";
                $data = \Illuminate\Support\Facades\DB::table("obe_nilai_cpmk")
                    ->join("mahasiswas", "mahasiswas.id", "=", "obe_nilai_cpmk.mahasiswa_id")
                    ->join("cpmks", "cpmks.id", "=", "obe_nilai_cpmk.cpmk_id")
                    ->select(
                        "mahasiswas.nim as NIM",
                        "mahasiswas.nama as Nama_Lengkap",
                        "cpmks.kode_cpmk as Kode_CPMK",
                        "cpmks.deskripsi_cpmk as Deskripsi",
                        "obe_nilai_cpmk.nilai as Nilai_Capaian"
                    )
                    ->orderBy("mahasiswas.nim")
                    ->get();
                break;

            // C.1 Budaya Mutu
EOD;

$content = str_replace('switch ($key) {
            // C.1 Budaya Mutu', $new_cases, $content);

file_put_contents('app/Http/Controllers/ObePortalController.php', $content);
echo "Added 5 new cases to pdfRecap.";
